[phases.setup]
nixPkgs = ["python39", "nodejs_18"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn --config gunicorn.conf.py api_server:app"